package eu.robm15.tenxdevs.service;

import eu.robm15.tenxdevs.repository.TripPlanRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;

/**
 * Service for managing AI usage limits per user.
 * Prevents abuse and controls costs by limiting the number of AI-generated plans.
 */
@Service
public class AIUsageLimitService {

    @Autowired
    private TripPlanRepository tripPlanRepository;

    /**
     * Maximum number of plans a user can generate per day
     * Default: 10 plans per day
     */
    @Value("${ai.usage.limit.daily:10}")
    private int dailyLimit;

    /**
     * Check if user has exceeded their daily AI usage limit
     *
     * @param userId Supabase user ID
     * @return true if user can generate more plans, false if limit exceeded
     */
    public boolean canGeneratePlan(String userId) {
        LocalDateTime startOfDay = LocalDateTime.now().withHour(0).withMinute(0).withSecond(0).withNano(0);
        long todayCount = tripPlanRepository.countByUserIdAndCreatedAtAfter(userId, startOfDay);

        return todayCount < dailyLimit;
    }

    /**
     * Get the number of plans generated by user today
     *
     * @param userId Supabase user ID
     * @return number of plans generated today
     */
    public long getTodayUsageCount(String userId) {
        LocalDateTime startOfDay = LocalDateTime.now().withHour(0).withMinute(0).withSecond(0).withNano(0);
        return tripPlanRepository.countByUserIdAndCreatedAtAfter(userId, startOfDay);
    }

    /**
     * Get the remaining number of plans user can generate today
     *
     * @param userId Supabase user ID
     * @return remaining plan generation count
     */
    public int getRemainingUsage(String userId) {
        long used = getTodayUsageCount(userId);
        return Math.max(0, dailyLimit - (int) used);
    }

    /**
     * Get the daily limit for plan generation
     *
     * @return daily limit
     */
    public int getDailyLimit() {
        return dailyLimit;
    }
}
